---
- name: Setup
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    image: ghcr.io/tetafro/cv
    tag: latest
    container: cv
  tasks:
    - name: Pull latest image
      docker_image:
        name: "{{ image }}:{{ tag }}"
        source: pull
        force_source: true

    - name: Remove current container
      docker_container:
        name: "{{ container }}"
        state: absent

    - name: Run new container
      docker_container:
        name: "{{ container }}"
        image: "{{ image }}:{{ tag }}"
        state: started
        restart_policy: always
        networks:
          - name: internal
        volumes:
          - "/home/{{ ansible_user }}/cv/logs:/app/logs"

    - name: Setup logs rotation
      become: true
      template:
        src: logrotate.conf.j2
        dest: /etc/logrotate.d/cv.conf
        owner: root
        group: root
        mode: "0644"
