---
- name: Setup
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull latest image
      command: docker pull ghcr.io/tetafro/cv:latest
      changed_when: true

    - name: Stop current container
      command: docker stop cv
      changed_when: true

    - name: Remove current container
      command: docker rm cv
      changed_when: true

    - name: Run latest image
      command: >
        docker run -d
        --restart unless-stopped
        --network internal
        --volume ~/logs:/app/logs
        --name cv
        ghcr.io/tetafro/cv:latest
      changed_when: true
